runtime: javascript
auto_add_examples: true
modules: []
task_examples:
  - initializeAgent
  - addFunction
  - addModule
  - updateHeaders
  - updateInstructions
  - listFunctions
  - getInstructions
  - runAdhocTask
